import Head from "next/head";
import Image from "next/image";
import Features from "../components/Features";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import { ToastContainer, toast } from "react-toastify";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Codeswear.com - wear the code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer />
      <img src="home.jpg" alt="" />
      <Features />
    </div>
  );
}
